output.. = bin/
bin.includes = META-INF/,\
               .,\
               OSGI-INF/tw.ninniku.booking.model.factory.xml,\
               OSGI-INF/tw.ninniku.booking.form.factory.xml,\
               OSGI-INF/tw.ninniku.booking.process.factory.xml,\
               WEB-INF/web/js/,\
               WEB-INF/web/styles/,\
               WEB-INF/web/images/,\
               src/,\
               WEB-INF/
source.. = src/
src.includes = src/
