output.. = bin/
bin.includes = META-INF/,\
               .,\
               OSGI-INF/tw.ninniku.booking.model.factory.xml,\
               OSGI-INF/tw.ninniku.booking.form.factory.xml,\
               OSGI-INF/tw.ninniku.booking.process.factory.xml,\
               web/,\
               src/
source.. = src/
src.includes = src/,\
               web/
